name: Publish to PyPI

on:
  push:
    tags:
      - v* # Trigger on any tag starting with 'v' (e.g., v1.0.0)
  workflow_dispatch: # Allow manual triggering

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/vibe-math-mcp/

    # Required permissions for PyPI Trusted Publishing
    permissions:
      id-token: write # OIDC token for PyPI trusted publishing
      contents: write # Write to repository for creating releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: dist/*
